(in-package :vfl-tools)
(defconstant   VT #\Vt)
(defconstant   TB #\Tab)
(defconstant   FF #\Page)
(defconstant   SP #\Space)
(defconstant   CR #\Return)
(defconstant   NL #\Newline)
(defparameter  WC '(VT TB FF SP CR))
(defparameter  WS (cons NL WC))
(defparameter EOS '(#\¶ #\§ #\) #\] #\} #\> nil))
(defparameter EOL (cons NL EOS))
(defvar *nl-pos*)
(defun   snl (s c) (? ((eq c NL) (setf *nl-pos* (p s)))) c)
(defun   off (s) (- (p s) *nl-pos*))
(defun peekc (s &optional  b)           (peek-char nil s b))
(defun readc (s &optional (b t)) (snl s (read-char     s b)))
(defun readr (s &optional (b t)) (read-preserving-whitespace s b))
(defun  wc-p (c) (member c  WC))
(defun  ws-p (c) (member c  WS))
(defun eos-p (c) (member c EOS))
(defun eol-p (c) (member c EOL))
(defun sym-p (c) (mv-bind (a b) (get-mchar c) (? (a b) (t t))))
(defun read-ws (s) (? ((member (peekc s) WS) (cons (readc s) (read-ws s)))))
(defun read-wc (s) (? ((member (peekc s) WC) (cons (readc s) (read-wc s)))))
(defun peek-wc (s) (read-wc s) (peekc s))
(defun read-xl (s)
  (? ((eol-p (peek-wc s)) (values))
     (t (cons (readr s) (read-xl s)))))
(defun read-xll (s x)
  (? ((eos-p (peek-wc s)) (values))
     (t (read-ws s)
	(let*                          (y (mv-list (read-xl  s)))
	  (read-wc s)
	  (^^ (? ((= (off s) x) (append y (mv-list (read-xll s x))))
		 (t             y)))))))
(defun read-nl (s c)
  (snl s c)
  (let* ((d (peek-wc s)))
    (? ((eq     d  NL) (values))
       ((member d EOS) (error "NFW"))
       (t (read-xll s (off s))))))
(defun read-dlist (c s)
  (? ((eq (peek-wc s) c) (n (readc s) nil))
     (t (cons (readr s) (read-dlist c s)))))
